import Darwin
import Foundation
import os.log

private let leafLogger = Logger(subsystem: "com.chenhuazhao.blaze", category: "Leaf")

/// Configuration that the controller materialises into a leaf `.conf` file
/// before launching the binary. Values map 1:1 onto leaf's General/Proxy/Rule
/// syntax — see `Vendor/Leaf/leaf/leaf/src/config/conf/config.rs` for the
/// canonical reference.
public struct LeafConfiguration: Sendable, Hashable {
    public var httpPort: Int
    public var socksPort: Int
    public var dnsServers: [String]
    /// Physical interface name (e.g. "en0", "en1") that leaf MUST use for all
    /// outbound dials. This bypasses the host's packet tunnel so the upstream
    /// connections do not loop back through Blaze.
    public var boundInterface: String?
    public var logLevel: String
    public var proxies: [Proxy]
    /// Routing rules, evaluated in order. The first match wins. Use `.final`
    /// at the end to fall through to a named proxy.
    public var rules: [Rule]
    /// Tag of the proxy/group that traffic should land on by default. Mostly
    /// matters when there are zero rules; otherwise the `.final` rule covers
    /// it.
    public var defaultProxy: String

    public struct Proxy: Sendable, Hashable {
        public var tag: String
        public var protocolName: String   // direct, drop, trojan, socks, shadowsocks, ...
        public var address: String?
        public var port: Int?
        public var password: String?
        public var sni: String?
        public var tlsInsecure: Bool
        public var ws: Bool
        public var wsPath: String?
        public var wsHost: String?
        public var encryptMethod: String?
        public var extra: [String: String]

        public init(
            tag: String,
            protocolName: String,
            address: String? = nil,
            port: Int? = nil,
            password: String? = nil,
            sni: String? = nil,
            tlsInsecure: Bool = false,
            ws: Bool = false,
            wsPath: String? = nil,
            wsHost: String? = nil,
            encryptMethod: String? = nil,
            extra: [String: String] = [:]
        ) {
            self.tag = tag
            self.protocolName = protocolName
            self.address = address
            self.port = port
            self.password = password
            self.sni = sni
            self.tlsInsecure = tlsInsecure
            self.ws = ws
            self.wsPath = wsPath
            self.wsHost = wsHost
            self.encryptMethod = encryptMethod
            self.extra = extra
        }
    }

    public struct Rule: Sendable, Hashable {
        public var kind: String     // DOMAIN, DOMAIN-SUFFIX, IP-CIDR, FINAL, ...
        public var value: String    // "" for FINAL
        public var target: String   // proxy tag

        public init(kind: String, value: String, target: String) {
            self.kind = kind
            self.value = value
            self.target = target
        }

        public static func final(_ target: String) -> Rule {
            Rule(kind: "FINAL", value: "", target: target)
        }
    }

    public init(
        httpPort: Int,
        socksPort: Int,
        dnsServers: [String],
        boundInterface: String?,
        logLevel: String = "info",
        proxies: [Proxy],
        rules: [Rule],
        defaultProxy: String
    ) {
        self.httpPort = httpPort
        self.socksPort = socksPort
        self.dnsServers = dnsServers
        self.boundInterface = boundInterface
        self.logLevel = logLevel
        self.proxies = proxies
        self.rules = rules
        self.defaultProxy = defaultProxy
    }

    /// Serialise to the leaf `.conf` ini-ish syntax. Comments preserve
    /// generator provenance so a config dropped in by hand can be told apart
    /// from one Blaze authored.
    public func renderConf() -> String {
        var lines: [String] = []
        lines.append("# Generated by Blaze LeafController. Do not edit by hand.")
        lines.append("")
        lines.append("[General]")
        lines.append("loglevel = \(logLevel)")
        if !dnsServers.isEmpty {
            lines.append("dns-server = \(dnsServers.joined(separator: ", "))")
        }
        lines.append("http-interface = 127.0.0.1")
        lines.append("http-port = \(httpPort)")
        lines.append("socks-interface = 127.0.0.1")
        lines.append("socks-port = \(socksPort)")
        lines.append("")
        lines.append("[Proxy]")
        for proxy in proxies {
            lines.append(Self.renderProxy(proxy))
        }
        if !rules.isEmpty {
            lines.append("")
            lines.append("[Rule]")
            for rule in rules {
                if rule.kind == "FINAL" {
                    lines.append("FINAL, \(rule.target)")
                } else {
                    lines.append("\(rule.kind), \(rule.value), \(rule.target)")
                }
            }
        }
        lines.append("")
        return lines.joined(separator: "\n")
    }

    private static func renderProxy(_ p: Proxy) -> String {
        switch p.protocolName {
        case "direct", "drop":
            return "\(p.tag) = \(p.protocolName)"
        default:
            break
        }
        var fields: [String] = [p.protocolName]
        if let address = p.address { fields.append(address) }
        if let port = p.port { fields.append(String(port)) }
        if let password = p.password { fields.append("password=\(password)") }
        if let sni = p.sni { fields.append("sni=\(sni)") }
        if let encryptMethod = p.encryptMethod { fields.append("encrypt-method=\(encryptMethod)") }
        if p.tlsInsecure { fields.append("tls-insecure=true") }
        if p.ws {
            fields.append("ws=true")
            if let wsPath = p.wsPath { fields.append("ws-path=\(wsPath)") }
            if let wsHost = p.wsHost { fields.append("ws-host=\(wsHost)") }
        }
        for (k, v) in p.extra.sorted(by: { $0.key < $1.key }) {
            fields.append("\(k)=\(v)")
        }
        return "\(p.tag) = \(fields.joined(separator: ", "))"
    }
}

/// Manages the lifecycle of an embedded `leaf` binary running as a subprocess.
/// Generates the leaf `.conf` file from a `LeafConfiguration`, launches the
/// binary, exposes liveness, and stops cleanly. Designed to be driven from a
/// single owner; protected by an actor so concurrent start/stop requests
/// serialise.
public actor LeafController {
    public enum LeafError: Error, LocalizedError {
        case binaryNotFound(URL)
        case launchFailed(String)
        case alreadyRunning
        case writeConfigFailed(String)

        public var errorDescription: String? {
            switch self {
            case .binaryNotFound(let url):
                return "leaf binary not found at \(url.path)"
            case .launchFailed(let message):
                return "leaf launch failed: \(message)"
            case .alreadyRunning:
                return "leaf is already running"
            case .writeConfigFailed(let message):
                return "leaf config write failed: \(message)"
            }
        }
    }

    private let binaryURL: URL
    private let runtimeDir: URL
    private var process: Process?
    private var stderrPipe: Pipe?
    private var stdoutPipe: Pipe?
    private var lastConfiguration: LeafConfiguration?
    private var lastConfigPath: URL?
    private var lastLogPath: URL?

    public init(binaryURL: URL, runtimeDir: URL) {
        self.binaryURL = binaryURL
        self.runtimeDir = runtimeDir
    }

    public var isRunning: Bool {
        process?.isRunning ?? false
    }

    public var pid: Int32? {
        process?.processIdentifier
    }

    public var configPath: URL? { lastConfigPath }
    public var logPath: URL? { lastLogPath }
    public var configuration: LeafConfiguration? { lastConfiguration }

    /// Starts leaf with the given configuration. If leaf is already running,
    /// throws `.alreadyRunning` — callers should `stop()` first when applying
    /// a new profile.
    public func start(with configuration: LeafConfiguration) async throws {
        if let process, process.isRunning {
            throw LeafError.alreadyRunning
        }

        guard FileManager.default.fileExists(atPath: binaryURL.path) else {
            throw LeafError.binaryNotFound(binaryURL)
        }

        try FileManager.default.createDirectory(at: runtimeDir, withIntermediateDirectories: true)
        let configURL = runtimeDir.appendingPathComponent("leaf.conf")
        let logURL = runtimeDir.appendingPathComponent("leaf.log")

        do {
            try configuration.renderConf().write(to: configURL, atomically: true, encoding: .utf8)
        } catch {
            throw LeafError.writeConfigFailed(error.localizedDescription)
        }

        let process = Process()
        process.executableURL = binaryURL
        var arguments = ["-c", configURL.path]
        if let bound = configuration.boundInterface, !bound.isEmpty {
            arguments.append(contentsOf: ["-b", bound])
        }
        process.arguments = arguments

        // Truncate log file so we don't accumulate runs forever; the file is
        // append-friendly via tee in the script-driven workflow, but for the
        // host app a clean file per launch is easier to read.
        FileManager.default.createFile(atPath: logURL.path, contents: nil)
        let logHandle = try FileHandle(forWritingTo: logURL)
        process.standardOutput = logHandle
        process.standardError = logHandle

        do {
            try process.run()
        } catch {
            try? logHandle.close()
            throw LeafError.launchFailed(error.localizedDescription)
        }

        self.process = process
        self.lastConfiguration = configuration
        self.lastConfigPath = configURL
        self.lastLogPath = logURL
        let pid = process.processIdentifier
        leafLogger.notice("leaf started pid=\(pid, privacy: .public) config=\(configURL.path, privacy: .public)")

        // Detach a watcher so a crash logs once we notice it.
        Task.detached { [weak self] in
            process.waitUntilExit()
            let status = process.terminationStatus
            let reason = process.terminationReason
            leafLogger.notice("leaf exited pid=\(pid, privacy: .public) status=\(status, privacy: .public) reason=\(String(describing: reason), privacy: .public)")
            await self?.handleExit()
        }
    }

    public func stop() async {
        guard let process, process.isRunning else {
            self.process = nil
            return
        }
        leafLogger.notice("leaf stopping pid=\(process.processIdentifier, privacy: .public)")
        process.terminate()
        // Give leaf a moment to flush; if it does not exit within 3s, send SIGKILL.
        let pid = process.processIdentifier
        let deadline = Date().addingTimeInterval(3.0)
        while process.isRunning && Date() < deadline {
            try? await Task.sleep(nanoseconds: 100_000_000)
        }
        if process.isRunning {
            leafLogger.notice("leaf still running after SIGTERM; sending SIGKILL pid=\(pid, privacy: .public)")
            kill(pid, SIGKILL)
        }
        self.process = nil
    }

    private func handleExit() {
        if let process, !process.isRunning {
            self.process = nil
        }
    }
}
